export * from "./header/Header";
export * from "./svgBackground/SvgBackground";
export * from "./home/Home";
export * from "./features/Features";
export * from "./partners/Partners";
export * from "./testimonials/Testimonials";
export * from "./pricing/Pricing";
export * from "./contact/Contact";
export * from "./footer/Footer";
